const APPLICATION_TYPES = {
  BIRTH: 'BIRTH',
  DEATH: 'DEATH', 
  TRADE_LICENSE: 'TRADE_LICENSE',
  NOC: 'NOC'
};

const APPLICATION_STATUS = {
  PENDING: 'PENDING',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED', 
  REJECTED: 'REJECTED',
  ISSUED: 'ISSUED',
 FORWARDED_TO_COMMISSIONER: 'FORWARDED_TO_COMMISSIONER'
};

const CREDENTIAL_STATUS = {
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  REVOKED: 'REVOKED'
};

const USER_ROLES = {
  OFFICER: 'OFFICER',
  ADMIN: 'ADMIN',
  COMMISSIONER: 'COMMISSIONER'
};

module.exports = {
  APPLICATION_TYPES,
  APPLICATION_STATUS,
  CREDENTIAL_STATUS,
  USER_ROLES
};